apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: influx
  namespace: default
spec:
  type: bindings.influx
  version: v1
  metadata:
  - name: url # Required
    value: https://westeurope-1.azure.cloud2.influxdata.com/orgs/4ae047279b793f6b
  - name: token # Required
    value: dV_0ZW9X-mXkxreKOT__RTNGNtF5V0IDEaI2M2ntLoIzMbW0WZ9yQ9u5m9C_tn_GruaqkNQIu15btq7bfzxGEQ==
  - name: org # Required
    value: 4ae047279b793f6b
  - name: bucket # Required
    value: fbb36c56945ef45f